<?php
/**
 * Custom WordPress login URL.
 *
 * @package TNStackToolkit
 */

defined( 'ABSPATH' ) || exit;

add_action( 'init', 'tnstack_custom_login_route_request', -999 );
add_action( 'init', 'tnstack_custom_login_block_default_admin', -998 );
add_action( 'login_init', 'tnstack_custom_login_block_default_url', -999 );
add_filter( 'site_url', 'tnstack_custom_login_filter_site_url', 10, 4 );
add_filter( 'network_site_url', 'tnstack_custom_login_filter_network_site_url', 10, 3 );
add_filter( 'wp_redirect', 'tnstack_custom_login_filter_redirect', 10, 2 );

/**
 * @return array<string, string>
 */
function tnstack_custom_login_defaults() {
	return array(
		'login_slug' => '',
	);
}

/**
 * Read settings without a request-level cache so a newly saved URL takes effect
 * immediately.
 *
 * @return array<string, string>
 */
function tnstack_custom_login_settings() {
	$stored = get_option( tnstack_module_option_key( 'custom-login-url' ), array() );
	$stored = is_array( $stored ) ? $stored : array();

	return wp_parse_args( $stored, tnstack_custom_login_defaults() );
}

/**
 * @param string $slug Raw login slug.
 * @return string
 */
function tnstack_custom_login_sanitize_slug( $slug ) {
	$slug = trim( wp_unslash( (string) $slug ) );
	$slug = trim( $slug, "/\\ \t\n\r\0\x0B" );
	$slug = sanitize_title( $slug );

	return substr( $slug, 0, 64 );
}

/**
 * @return string
 */
function tnstack_custom_login_slug() {
	if ( defined( 'TNSTACK_DISABLE_CUSTOM_LOGIN' ) && TNSTACK_DISABLE_CUSTOM_LOGIN ) {
		return '';
	}

	$settings = tnstack_custom_login_settings();

	return tnstack_custom_login_sanitize_slug( $settings['login_slug'] ?? '' );
}

/**
 * @return bool
 */
function tnstack_custom_login_is_enabled() {
	return '' !== tnstack_custom_login_slug();
}

/**
 * @param array<string, string> $args Optional query arguments.
 * @return string
 */
function tnstack_custom_login_url( $args = array() ) {
	$slug = tnstack_custom_login_slug();

	if ( '' === $slug ) {
		return site_url( 'wp-login.php', 'login' );
	}

	$url = home_url( '/' . rawurlencode( $slug ) . '/' );

	return $args ? add_query_arg( $args, $url ) : $url;
}

/**
 * Replace wp-login.php in a generated URL.
 *
 * @param string $url URL generated by WordPress.
 * @return string
 */
function tnstack_custom_login_replace_url( $url ) {
	$slug = tnstack_custom_login_slug();

	if ( '' === $slug || false === strpos( $url, 'wp-login.php' ) ) {
		return $url;
	}

	$custom_url = home_url( '/' . rawurlencode( $slug ) . '/' );
	$scheme     = wp_parse_url( $url, PHP_URL_SCHEME );
	$query      = wp_parse_url( $url, PHP_URL_QUERY );
	$fragment   = wp_parse_url( $url, PHP_URL_FRAGMENT );

	if ( in_array( $scheme, array( 'http', 'https' ), true ) ) {
		$custom_url = set_url_scheme( $custom_url, $scheme );
	}

	if ( is_string( $query ) && '' !== $query ) {
		$custom_url .= '?' . $query;
	}

	if ( is_string( $fragment ) && '' !== $fragment ) {
		$custom_url .= '#' . $fragment;
	}

	return $custom_url;
}

/**
 * @param string   $url     Complete site URL.
 * @param string   $path    Path relative to the site URL.
 * @param string|null $scheme URL scheme.
 * @param int|null $blog_id Site ID.
 * @return string
 */
function tnstack_custom_login_filter_site_url( $url, $path, $scheme, $blog_id ) {
	unset( $path, $scheme, $blog_id );

	return tnstack_custom_login_replace_url( $url );
}

/**
 * @param string      $url    Complete network URL.
 * @param string      $path   Path relative to the network URL.
 * @param string|null $scheme URL scheme.
 * @return string
 */
function tnstack_custom_login_filter_network_site_url( $url, $path, $scheme ) {
	unset( $path, $scheme );

	return tnstack_custom_login_replace_url( $url );
}

/**
 * Catch the few WordPress login redirects that use a relative wp-login.php
 * string instead of site_url().
 *
 * @param string $location Redirect destination.
 * @param int    $status   HTTP status.
 * @return string
 */
function tnstack_custom_login_filter_redirect( $location, $status ) {
	unset( $status );

	return tnstack_custom_login_replace_url( $location );
}

/**
 * Determine whether the current front-controller request matches the custom
 * login path.
 *
 * @return bool
 */
function tnstack_custom_login_is_custom_request() {
	$slug = tnstack_custom_login_slug();

	if ( '' === $slug || empty( $_SERVER['REQUEST_URI'] ) ) {
		return false;
	}

	$request_path = wp_parse_url( wp_unslash( $_SERVER['REQUEST_URI'] ), PHP_URL_PATH );
	$home_path    = wp_parse_url( home_url( '/' ), PHP_URL_PATH );
	$request_path = trim( rawurldecode( (string) $request_path ), '/' );
	$home_path    = trim( rawurldecode( (string) $home_path ), '/' );

	if ( '' !== $home_path ) {
		if ( $request_path === $home_path ) {
			return false;
		}

		if ( 0 !== strpos( $request_path, $home_path . '/' ) ) {
			return false;
		}

		$request_path = substr( $request_path, strlen( $home_path ) + 1 );
	}

	return $slug === trim( $request_path, '/' );
}

/**
 * Serve wp-login.php at the configured custom path.
 */
function tnstack_custom_login_route_request() {
	if ( ! tnstack_custom_login_is_custom_request() ) {
		return;
	}

	/*
	 * wp-login.php normally runs in the global scope. Import the variables its
	 * helper functions expect so including it from this route callback behaves
	 * exactly like a direct request.
	 */
	global $action, $error, $interim_login, $user_login;

	if ( ! isset( $error ) ) {
		$error = '';
	}

	if ( ! isset( $user_login ) ) {
		$user_login = '';
	}

	if ( ! defined( 'TNSTACK_CUSTOM_LOGIN_REQUEST' ) ) {
		define( 'TNSTACK_CUSTOM_LOGIN_REQUEST', true );
	}

	$GLOBALS['pagenow'] = 'wp-login.php';

	require ABSPATH . 'wp-login.php';
	exit;
}

/**
 * Return the current request path relative to the WordPress installation URL.
 *
 * @return string
 */
function tnstack_custom_login_admin_relative_path() {
	$request_path = wp_parse_url( wp_unslash( $_SERVER['REQUEST_URI'] ?? '' ), PHP_URL_PATH );
	$site_path    = wp_parse_url( site_url( '/' ), PHP_URL_PATH );
	$request_path = trim( rawurldecode( (string) $request_path ), '/' );
	$site_path    = trim( rawurldecode( (string) $site_path ), '/' );

	if ( '' !== $site_path ) {
		if ( 0 !== strpos( $request_path, $site_path . '/' ) ) {
			return '';
		}
		$request_path = substr( $request_path, strlen( $site_path ) + 1 );
	}

	return trim( $request_path, '/' );
}

/**
 * Block the default admin path for visitors when a custom login URL is active.
 * Frontend AJAX and unauthenticated admin-post handlers remain available.
 */
function tnstack_custom_login_block_default_admin() {
	if ( ! tnstack_custom_login_is_enabled() || is_user_logged_in() ) {
		return;
	}

	if ( ( defined( 'WP_CLI' ) && WP_CLI ) || wp_doing_ajax() || wp_doing_cron() ) {
		return;
	}

	$path = tnstack_custom_login_admin_relative_path();
	if ( 'wp-admin' !== $path && 0 !== strpos( $path, 'wp-admin/' ) ) {
		return;
	}

	if ( in_array( $path, array( 'wp-admin/admin-ajax.php', 'wp-admin/admin-post.php' ), true ) ) {
		return;
	}

	tnstack_custom_login_deny_404();
}

/** Send a generic 404 response without revealing the login URL. */
function tnstack_custom_login_deny_404() {
	status_header( 404 );
	nocache_headers();
	wp_die(
		esc_html__( 'Không tìm thấy trang.', 'tnstack-toolkit' ),
		esc_html__( 'Không tìm thấy', 'tnstack-toolkit' ),
		array( 'response' => 404 )
	);
}

/**
 * Return a generic 404 for direct requests to wp-login.php.
 */
function tnstack_custom_login_block_default_url() {
	if ( ! tnstack_custom_login_is_enabled() || defined( 'TNSTACK_CUSTOM_LOGIN_REQUEST' ) ) {
		return;
	}

	if ( defined( 'WP_CLI' ) && WP_CLI ) {
		return;
	}

	tnstack_custom_login_deny_404();
}

/**
 * Render module settings.
 */
function tnstack_custom_login_render_admin() {
	if ( ! current_user_can( TNStack_Account_Permissions::MANAGE_CAP ) ) {
		return;
	}

	$settings = tnstack_custom_login_settings();
	$notice   = '';
	$error    = '';

	if ( isset( $_POST['tnstack_custom_login_save'] ) ) {
		check_admin_referer( 'tnstack_custom_login' );

		$slug     = tnstack_custom_login_sanitize_slug( $_POST['login_slug'] ?? '' );
		$reserved = array( 'wp-admin', 'wp-login', 'wp-login-php', 'wp-json', 'feed', 'admin', 'login' );

		if ( in_array( $slug, $reserved, true ) ) {
			$error = __( 'Đường dẫn này được WordPress dành riêng. Vui lòng chọn đường dẫn khác.', 'tnstack-toolkit' );
		} else {
			$settings = tnstack_module_update_settings(
				'custom-login-url',
				array( 'login_slug' => $slug ),
				tnstack_custom_login_defaults()
			);
			$notice = '' === $slug
				? __( 'Đã tắt URL đăng nhập tùy chỉnh. Bạn có thể dùng lại wp-login.php.', 'tnstack-toolkit' )
				: __( 'Đã lưu URL đăng nhập mới. Hãy lưu đường dẫn này trước khi đăng xuất.', 'tnstack-toolkit' );
		}
	}

	$login_slug = tnstack_custom_login_sanitize_slug( $settings['login_slug'] ?? '' );
	$login_url  = '' !== $login_slug ? home_url( '/' . rawurlencode( $login_slug ) . '/' ) : '';
	?>
	<div class="wrap ttk-settings ttk-settings--login">
		<header class="ttk-settings__hero">
			<span class="ttk-settings__hero-icon"><span class="dashicons dashicons-lock"></span></span>
			<div>
				<span class="ttk-settings__eyebrow"><?php esc_html_e( 'TNStack Toolkit', 'tnstack-toolkit' ); ?></span>
				<h1><?php esc_html_e( 'Custom Login URL', 'tnstack-toolkit' ); ?></h1>
				<p><?php esc_html_e( 'Ẩn đường dẫn đăng nhập mặc định và giảm truy cập tự động vào trang quản trị.', 'tnstack-toolkit' ); ?></p>
			</div>
		</header>

		<?php if ( $notice ) : ?>
			<div class="notice notice-success is-dismissible"><p><?php echo esc_html( $notice ); ?></p></div>
		<?php endif; ?>

		<?php if ( $error ) : ?>
			<div class="notice notice-error is-dismissible"><p><?php echo esc_html( $error ); ?></p></div>
		<?php endif; ?>

		<form method="post">
			<?php wp_nonce_field( 'tnstack_custom_login' ); ?>
			<section class="ttk-settings__card">
				<div class="ttk-settings__card-header">
					<h2><?php esc_html_e( 'Đường dẫn bảo mật', 'tnstack-toolkit' ); ?></h2>
					<p><?php esc_html_e( 'Dùng chữ thường, chữ số và dấu gạch ngang để tạo URL dễ ghi nhớ.', 'tnstack-toolkit' ); ?></p>
				</div>
				<table class="form-table" role="presentation">
					<tr>
						<th scope="row"><label for="login_slug"><?php esc_html_e( 'Đường dẫn đăng nhập', 'tnstack-toolkit' ); ?></label></th>
						<td>
							<div class="ttk-settings__url-field">
								<code><?php echo esc_html( trailingslashit( home_url() ) ); ?></code>
								<input name="login_slug" id="login_slug" type="text" value="<?php echo esc_attr( $login_slug ); ?>" placeholder="dang-nhap-bao-mat" autocomplete="off">
							</div>
							<p class="description"><?php esc_html_e( 'Chỉ nhập phần đường dẫn. Để trống để tắt tính năng.', 'tnstack-toolkit' ); ?></p>
						</td>
					</tr>
				</table>

				<?php if ( $login_url ) : ?>
					<div class="ttk-settings__status">
						<span class="dashicons dashicons-warning"></span>
						<div>
							<p>
								<strong><?php esc_html_e( 'URL đăng nhập hiện tại:', 'tnstack-toolkit' ); ?></strong>
								<a href="<?php echo esc_url( $login_url ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html( $login_url ); ?></a>
							</p>
							<p><?php esc_html_e( 'Hãy lưu URL này trước khi đăng xuất. wp-login.php và wp-admin sẽ trả về lỗi 404 cho khách chưa đăng nhập.', 'tnstack-toolkit' ); ?></p>
						</div>
					</div>
				<?php endif; ?>
			</section>

			<div class="ttk-settings__recovery">
				<span class="dashicons dashicons-sos"></span>
				<p>
					<strong><?php esc_html_e( 'Khôi phục khẩn cấp:', 'tnstack-toolkit' ); ?></strong>
					<?php esc_html_e( 'thêm', 'tnstack-toolkit' ); ?>
					<code>define( 'TNSTACK_DISABLE_CUSTOM_LOGIN', true );</code>
					<?php esc_html_e( 'vào wp-config.php để dùng lại wp-login.php.', 'tnstack-toolkit' ); ?>
				</p>
			</div>

			<div class="ttk-settings__actions">
				<?php submit_button( __( 'Lưu thay đổi', 'tnstack-toolkit' ), 'primary', 'tnstack_custom_login_save' ); ?>
			</div>
		</form>
	</div>
	<?php
}
