<?php
/** Generic CRM/webhook delivery for form submissions. */
defined( 'ABSPATH' ) || exit;
final class TNStack_Popup_Webhooks {
	const OPTION='tnstack_webhook_endpoints'; const LOG='tnstack_webhook_logs';
	public static function init(){add_action('admin_menu',array(__CLASS__,'menu'),32);add_action('admin_post_tnstack_save_webhooks',array(__CLASS__,'save'));add_action('admin_post_tnstack_test_webhook',array(__CLASS__,'test'));add_action('admin_post_tnstack_retry_webhook',array(__CLASS__,'retry'));add_action('tnstack_form_submitted',array(__CLASS__,'submitted'),10,1);add_filter('wp_privacy_personal_data_erasers',array(__CLASS__,'privacy_erasers'));}
	public static function menu(){add_submenu_page(TNStack_Toolkit_Features_Dashboard::PAGE_SLUG,'Webhook & CRM','Webhook & CRM',TNStack_Account_Permissions::MANAGE_CAP,'tnstack-webhooks',array(__CLASS__,'page'));}
	private static function guard($nonce){if(!current_user_can(TNStack_Account_Permissions::MANAGE_CAP))wp_die('Bạn không có quyền.');check_admin_referer($nonce);}
	public static function endpoints(){return(array)get_option(self::OPTION,array());}
	public static function submitted($payload){$payload['event']='form.submitted';$payload['site']=array('name'=>get_bloginfo('name'),'url'=>home_url('/'));$payload['created_at']=gmdate('c');foreach(self::endpoints()as$i=>$endpoint)if(!empty($endpoint['active'])&&!empty($endpoint['url']))self::send($i,$endpoint,$payload);}
	private static function send($index,$endpoint,$payload){$body=wp_json_encode($payload);$headers=array('Content-Type'=>'application/json','X-TNStack-Event'=>'form.submitted');if(!empty($endpoint['secret']))$headers['X-TNStack-Signature']='sha256='.hash_hmac('sha256',$body,$endpoint['secret']);$response=wp_safe_remote_post($endpoint['url'],array('timeout'=>12,'redirection'=>2,'headers'=>$headers,'body'=>$body));$ok=!is_wp_error($response)&&wp_remote_retrieve_response_code($response)>=200&&wp_remote_retrieve_response_code($response)<300;$logs=(array)get_option(self::LOG,array());array_unshift($logs,array('id'=>wp_generate_uuid4(),'time'=>time(),'endpoint'=>$endpoint['name']?:$endpoint['url'],'index'=>$index,'status'=>$ok?'success':'failed','code'=>is_wp_error($response)?0:wp_remote_retrieve_response_code($response),'message'=>is_wp_error($response)?$response->get_error_message():wp_html_excerpt(wp_remote_retrieve_body($response),180,'…'),'payload'=>$ok?array():$payload));update_option(self::LOG,array_slice($logs,0,100),false);return $ok;}
	public static function save(){self::guard('tnstack_save_webhooks');$rows=array();foreach(array_slice((array)($_POST['endpoints']??array()),0,3)as$row){$url=esc_url_raw(wp_unslash($row['url']??''));if(!$url)continue;$rows[]=array('name'=>sanitize_text_field(wp_unslash($row['name']??'')),'url'=>$url,'secret'=>sanitize_text_field(wp_unslash($row['secret']??'')),'active'=>empty($row['active'])?0:1);}update_option(self::OPTION,$rows,false);wp_safe_redirect(add_query_arg('saved','1',admin_url('admin.php?page=tnstack-webhooks')));exit;}
	public static function test(){self::guard('tnstack_test_webhook');$i=absint($_POST['index']??0);$all=self::endpoints();if(isset($all[$i]))self::send($i,$all[$i],array('event'=>'webhook.test','message'=>'Kết nối thử từ TNStack Toolkit','site'=>home_url('/'),'created_at'=>gmdate('c')));wp_safe_redirect(admin_url('admin.php?page=tnstack-webhooks'));exit;}
	public static function retry(){self::guard('tnstack_retry_webhook');$id=sanitize_text_field(wp_unslash($_POST['log_id']??''));$all=self::endpoints();foreach((array)get_option(self::LOG,array())as$log)if(($log['id']??'')===$id&&isset($all[$log['index']])){self::send($log['index'],$all[$log['index']],$log['payload']);break;}wp_safe_redirect(admin_url('admin.php?page=tnstack-webhooks'));exit;}
	public static function privacy_erasers($erasers){$erasers['tnstack-webhook-logs']=array('eraser_friendly_name'=>'TNStack Webhook Logs','callback'=>array(__CLASS__,'privacy_erase'));return $erasers;}
	public static function privacy_erase($email,$page=1){$logs=(array)get_option(self::LOG,array());$kept=array();$removed=false;foreach($logs as$log){$logged=sanitize_email($log['payload']['fields']['email']??'');if($logged&&$logged===sanitize_email($email)){$removed=true;continue;}$kept[]=$log;}if($removed)update_option(self::LOG,$kept,false);return array('items_removed'=>$removed,'items_retained'=>false,'messages'=>array(),'done'=>true);}
	public static function page(){if(!current_user_can(TNStack_Account_Permissions::MANAGE_CAP))return;$rows=self::endpoints();while(count($rows)<3)$rows[]=array('name'=>'','url'=>'','secret'=>'','active'=>0);$logs=(array)get_option(self::LOG,array());?>
	<div class="wrap ttk-webhooks"><h1>Webhook & CRM</h1><p>Gửi yêu cầu liên hệ theo JSON đến CRM, Make, n8n, Google Sheets hoặc hệ thống riêng.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('tnstack_save_webhooks'); ?><input type="hidden" name="action" value="tnstack_save_webhooks"><table class="widefat striped"><thead><tr><th>Bật</th><th>Tên kết nối</th><th>Webhook URL</th><th>Secret ký HMAC</th><th></th></tr></thead><tbody><?php foreach($rows as$i=>$row): ?><tr><td><input type="checkbox" name="endpoints[<?php echo $i; ?>][active]" value="1" <?php checked(!empty($row['active'])); ?>></td><td><input class="widefat" name="endpoints[<?php echo $i; ?>][name]" value="<?php echo esc_attr($row['name']); ?>" placeholder="CRM bán hàng"></td><td><input type="url" class="widefat" name="endpoints[<?php echo $i; ?>][url]" value="<?php echo esc_attr($row['url']); ?>" placeholder="https://..."></td><td><input class="widefat" name="endpoints[<?php echo $i; ?>][secret]" value="<?php echo esc_attr($row['secret']); ?>"></td><td><?php if(!empty($row['url'])):?><button class="button" form="test-<?php echo $i; ?>">Kiểm tra</button><?php endif;?></td></tr><?php endforeach; ?></tbody></table><?php submit_button('Lưu kết nối'); ?></form><?php foreach(self::endpoints()as$i=>$row): ?><form id="test-<?php echo $i; ?>" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('tnstack_test_webhook'); ?><input type="hidden" name="action" value="tnstack_test_webhook"><input type="hidden" name="index" value="<?php echo $i; ?>"></form><?php endforeach; ?><h2>100 lần gửi gần nhất</h2><table class="widefat striped"><thead><tr><th>Thời gian</th><th>Kết nối</th><th>Trạng thái</th><th>HTTP</th><th>Phản hồi</th><th></th></tr></thead><tbody><?php if(!$logs):?><tr><td colspan="6">Chưa có dữ liệu.</td></tr><?php else:foreach($logs as$log):?><tr><td><?php echo esc_html(wp_date('d/m/Y H:i:s',$log['time']));?></td><td><?php echo esc_html($log['endpoint']);?></td><td><strong class="is-<?php echo esc_attr($log['status']);?>"><?php echo $log['status']==='success'?'Thành công':'Thất bại';?></strong></td><td><?php echo absint($log['code']);?></td><td><?php echo esc_html($log['message']);?></td><td><?php if($log['status']==='failed'):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('tnstack_retry_webhook');?><input type="hidden" name="action" value="tnstack_retry_webhook"><input type="hidden" name="log_id" value="<?php echo esc_attr($log['id']);?>"><button class="button button-small">Gửi lại</button></form><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div><style>.ttk-webhooks{max-width:1250px}.ttk-webhooks table input{min-width:120px}.ttk-webhooks .is-success{color:#15803d}.ttk-webhooks .is-failed{color:#b91c1c}</style><?php }
}
TNStack_Popup_Webhooks::init();
