<?php
/** Multiple popup forms and display rules. */
defined( 'ABSPATH' ) || exit;

final class TNStack_Popup_Forms {
	const POST_TYPE = 'tnstack_form';
	public static function init() {
		add_action( 'init', array( __CLASS__, 'register' ) );
		add_action( 'admin_menu', array( __CLASS__, 'menu' ), 25 );
		add_action( 'add_meta_boxes', array( __CLASS__, 'box' ) );
		add_action( 'save_post_' . self::POST_TYPE, array( __CLASS__, 'save' ) );
		add_action( 'wp_footer', array( __CLASS__, 'configs' ), 30 );
		add_shortcode( 'tn_popup_trigger', array( __CLASS__, 'shortcode' ) );
	}
	public static function register() { register_post_type( self::POST_TYPE, array( 'labels'=>array('name'=>'Biểu mẫu Popup','singular_name'=>'Biểu mẫu','add_new_item'=>'Thêm biểu mẫu','edit_item'=>'Sửa biểu mẫu'), 'public'=>false, 'show_ui'=>true, 'show_in_menu'=>false, 'supports'=>array('title'), 'capability_type'=>'post', 'map_meta_cap'=>true ) ); }
	public static function menu() { add_submenu_page( TNStack_Toolkit_Features_Dashboard::PAGE_SLUG, 'Biểu mẫu Popup', 'Biểu mẫu Popup', TNStack_Account_Permissions::MANAGE_CAP, 'edit.php?post_type=' . self::POST_TYPE ); }
	public static function box() { add_meta_box( 'tnstack-form-options', 'Nội dung và quy tắc hiển thị', array(__CLASS__,'render_box'), self::POST_TYPE, 'normal', 'high' ); }
	public static function render_box( $post ) {
		wp_nonce_field('tnstack_form_save','tnstack_form_nonce'); $m=function($key,$default='')use($post){$v=get_post_meta($post->ID,'_tnf_'.$key,true);return $v===''?$default:$v;}; ?>
		<style>.tnf-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.tnf-grid label{display:block;font-weight:600}.tnf-grid input,.tnf-grid select,.tnf-grid textarea{width:100%;margin-top:6px}.tnf-wide{grid-column:1/-1}@media(max-width:782px){.tnf-grid{grid-template-columns:1fr}.tnf-wide{grid-column:auto}}</style>
		<div class="tnf-grid"><label>Tiêu đề<input name="tnf[title]" value="<?php echo esc_attr($m('title',$post->post_title)); ?>"></label><label>Nội dung nút gửi<input name="tnf[button_text]" value="<?php echo esc_attr($m('button_text','Gửi thông tin')); ?>"></label><label class="tnf-wide">Mô tả<textarea rows="3" name="tnf[description]"><?php echo esc_textarea($m('description')); ?></textarea></label><label>Email nhận<input type="email" name="tnf[recipient]" value="<?php echo esc_attr($m('recipient',get_option('admin_email'))); ?>"></label><label>Tiêu đề email<input name="tnf[subject]" value="<?php echo esc_attr($m('subject','Khách hàng gửi form Popup')); ?>"></label><label class="tnf-wide">Thông báo thành công<input name="tnf[success]" value="<?php echo esc_attr($m('success','Cảm ơn bạn! Chúng tôi sẽ liên hệ sớm.')); ?>"></label>
		<label>Kích hoạt<select name="tnf[trigger]"><?php foreach(array('manual'=>'Chỉ khi bấm nút','delay'=>'Sau một khoảng thời gian','scroll'=>'Khi cuộn trang','exit'=>'Khi rời trang') as $v=>$l) echo '<option value="'.esc_attr($v).'" '.selected($m('trigger','manual'),$v,false).'>'.esc_html($l).'</option>'; ?></select></label><label>Độ trễ (giây)<input type="number" min="0" max="3600" name="tnf[delay]" value="<?php echo esc_attr($m('delay','5')); ?>"></label><label>Phần trăm cuộn<input type="number" min="1" max="100" name="tnf[scroll]" value="<?php echo esc_attr($m('scroll','50')); ?>"></label><label><span>Hiển thị</span><select name="tnf[show_once]"><option value="0" <?php selected($m('show_once'),'0'); ?>>Mỗi lần tải trang</option><option value="1" <?php selected($m('show_once'),'1'); ?>>Một lần / 30 ngày</option></select></label><label class="tnf-wide">Chỉ hiển thị tại đường dẫn<textarea rows="3" name="tnf[include_paths]" placeholder="/san-pham/* (mỗi dòng một đường dẫn)"><?php echo esc_textarea($m('include_paths')); ?></textarea></label><label class="tnf-wide">Không hiển thị tại đường dẫn<textarea rows="3" name="tnf[exclude_paths]" placeholder="/gio-hang/*"><?php echo esc_textarea($m('exclude_paths')); ?></textarea></label></div><p class="description">Form này dùng bộ trường đã cấu hình trong Popup Form mặc định. Shortcode nút mở form: <code>[tn_popup_trigger id="<?php echo absint($post->ID); ?>" label="Liên hệ"]</code></p><?php
	}
	public static function save( $id ) { if(!isset($_POST['tnstack_form_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tnstack_form_nonce'])),'tnstack_form_save')||!current_user_can('edit_post',$id))return;$in=(array)($_POST['tnf']??array());foreach(array('title','button_text','subject','success','trigger')as$key)update_post_meta($id,'_tnf_'.$key,sanitize_text_field(wp_unslash($in[$key]??'')));update_post_meta($id,'_tnf_recipient',sanitize_email(wp_unslash($in['recipient']??'')));foreach(array('description','include_paths','exclude_paths')as$key)update_post_meta($id,'_tnf_'.$key,sanitize_textarea_field(wp_unslash($in[$key]??'')));update_post_meta($id,'_tnf_delay',min(3600,absint($in['delay']??5)));update_post_meta($id,'_tnf_scroll',max(1,min(100,absint($in['scroll']??50))));update_post_meta($id,'_tnf_show_once',empty($in['show_once'])?'0':'1'); }
	public static function settings( $id, $defaults ) { if(!$id||self::POST_TYPE!==get_post_type($id))return $defaults;foreach(array('title','description','button_text','success','recipient','subject')as$key){$v=get_post_meta($id,'_tnf_'.$key,true);if($v!=='')$defaults[$key]=$v;}return $defaults; }
	private static function matches( $patterns, $path ) { $patterns=preg_split('/[\r\n,]+/',(string)$patterns);foreach($patterns as$p){$p=trim($p);if($p!==''&&fnmatch($p,$path))return true;}return false; }
	public static function has_forms(){return(bool)get_posts(array('post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>1,'fields'=>'ids'));}
	public static function configs() { $path=wp_parse_url(home_url(wp_unslash($_SERVER['REQUEST_URI']??'/')),PHP_URL_PATH);$forms=get_posts(array('post_type'=>self::POST_TYPE,'post_status'=>'publish','posts_per_page'=>-1));foreach($forms as$f){$inc=get_post_meta($f->ID,'_tnf_include_paths',true);$exc=get_post_meta($f->ID,'_tnf_exclude_paths',true);if(($inc&&!self::matches($inc,$path))||($exc&&self::matches($exc,$path)))continue;$data=array('id'=>$f->ID,'title'=>get_post_meta($f->ID,'_tnf_title',true)?:$f->post_title,'description'=>get_post_meta($f->ID,'_tnf_description',true),'button'=>get_post_meta($f->ID,'_tnf_button_text',true)?:'Gửi thông tin','trigger'=>get_post_meta($f->ID,'_tnf_trigger',true)?:'manual','delay'=>absint(get_post_meta($f->ID,'_tnf_delay',true))*1000,'scroll'=>absint(get_post_meta($f->ID,'_tnf_scroll',true))?:50,'once'=>get_post_meta($f->ID,'_tnf_show_once',true)==='1');echo '<script type="application/json" class="tnpf-config">'.wp_json_encode($data).'</script>'; } }
	public static function shortcode( $atts ) { $a=shortcode_atts(array('id'=>0,'label'=>'Liên hệ'),$atts,'tn_popup_trigger');if(!absint($a['id']))return '';return '<button type="button" class="tnpf-trigger" data-tn-popup-open data-form-id="'.absint($a['id']).'">'.esc_html($a['label']).'</button>'; }
}
TNStack_Popup_Forms::init();
