<?php
/** CSV import/export for catalog products. */
defined( 'ABSPATH' ) || exit;
final class Slim_Catalog_Import_Export {
	public static function init() { add_action( 'admin_menu', array( __CLASS__, 'menu' ) ); add_action( 'admin_post_slim_catalog_export', array( __CLASS__, 'export' ) ); add_action( 'admin_post_slim_catalog_import', array( __CLASS__, 'import' ) ); }
	public static function menu() { add_submenu_page( 'edit.php?post_type=' . Slim_Catalog_Post_Types::POST_TYPE, 'Nhập / Xuất CSV', 'Nhập / Xuất CSV', 'manage_options', 'slim-catalog-import-export', array( __CLASS__, 'page' ) ); }
	public static function page() { ?>
	<div class="wrap sc-import-export"><h1>Nhập / Xuất sản phẩm</h1><?php if ( isset( $_GET['imported'] ) ) : ?><div class="notice notice-success"><p>Đã xử lý <?php echo esc_html( absint( $_GET['imported'] ) ); ?> sản phẩm, bỏ qua <?php echo esc_html( absint( $_GET['skipped'] ?? 0 ) ); ?> dòng.</p></div><?php endif; ?><div class="sc-ie-grid"><section><span class="dashicons dashicons-download"></span><h2>Xuất sản phẩm</h2><p>Tải toàn bộ sản phẩm, giá, danh mục và thiết lập nút mua hàng thành CSV UTF-8.</p><a class="button button-primary" href="<?php echo esc_url( wp_nonce_url( admin_url( 'admin-post.php?action=slim_catalog_export' ), 'slim_catalog_export' ) ); ?>">Tải file CSV</a></section><section><span class="dashicons dashicons-upload"></span><h2>Nhập sản phẩm</h2><p>Cập nhật theo SKU hoặc tạo sản phẩm mới. Cột bắt buộc: <code>name</code>; nên có <code>sku</code>.</p><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" enctype="multipart/form-data"><input type="hidden" name="action" value="slim_catalog_import"><?php wp_nonce_field( 'slim_catalog_import' ); ?><input type="file" name="csv" accept=".csv,text/csv" required><p><label><input type="checkbox" name="dry_run" value="1"> Chỉ kiểm tra, không lưu</label></p><button class="button button-primary">Nhập CSV</button></form></section></div><h2>Các cột hỗ trợ</h2><code>id, name, slug, status, sku, regular_price, sale_price, short_description, description, categories, featured, badge, cta_mode, cta_label, cta_hotline, cta_url, cta_recipient</code></div><style>.sc-import-export{max-width:1000px}.sc-ie-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:20px 0}.sc-ie-grid section{padding:26px;border:1px solid #dbe3ef;border-radius:16px;background:#fff;box-shadow:0 5px 18px rgba(15,23,42,.05)}.sc-ie-grid .dashicons{width:42px;height:42px;color:#2563eb;font-size:42px}@media(max-width:700px){.sc-ie-grid{grid-template-columns:1fr}}</style><?php }
	private static function headers() { return array( 'id','name','slug','status','sku','regular_price','sale_price','short_description','description','categories','featured','badge','cta_mode','cta_label','cta_hotline','cta_url','cta_recipient','cta_form_id','brand','stock_status' ); }
	public static function export() { if ( ! current_user_can( 'manage_options' ) ) wp_die( 'Không có quyền.' ); check_admin_referer( 'slim_catalog_export' ); $posts = get_posts( array( 'post_type' => Slim_Catalog_Post_Types::POST_TYPE, 'post_status' => array( 'publish','draft','private' ), 'posts_per_page' => -1 ) ); nocache_headers(); header( 'Content-Type: text/csv; charset=UTF-8' ); header( 'Content-Disposition: attachment; filename="tnstack-products-' . gmdate('Y-m-d') . '.csv"' ); $out=fopen('php://output','w'); fwrite($out,"\xEF\xBB\xBF"); fputcsv($out,self::headers()); foreach($posts as $p){$terms=wp_get_post_terms($p->ID,Slim_Catalog_Post_Types::TAXONOMY,array('fields'=>'names'));fputcsv($out,array($p->ID,$p->post_title,$p->post_name,$p->post_status,get_post_meta($p->ID,'_slim_sku',true),get_post_meta($p->ID,'_slim_price',true),get_post_meta($p->ID,'_slim_sale_price',true),get_post_meta($p->ID,'_slim_short_description',true),$p->post_content,implode('|',is_wp_error($terms)?array():$terms),get_post_meta($p->ID,'_slim_featured',true),get_post_meta($p->ID,'_slim_badge',true),get_post_meta($p->ID,'_slim_cta_mode',true),get_post_meta($p->ID,'_slim_cta_label',true),get_post_meta($p->ID,'_slim_cta_hotline',true),get_post_meta($p->ID,'_slim_cta_url',true),get_post_meta($p->ID,'_slim_cta_recipient',true),get_post_meta($p->ID,'_slim_cta_form_id',true),get_post_meta($p->ID,'_slim_brand',true),get_post_meta($p->ID,'_slim_stock_status',true)));} fclose($out);exit; }
	public static function import() { if(!current_user_can('manage_options'))wp_die('Không có quyền.');check_admin_referer('slim_catalog_import');if(empty($_FILES['csv']['tmp_name'])||!is_uploaded_file($_FILES['csv']['tmp_name']))wp_die('File CSV không hợp lệ.');$handle=fopen($_FILES['csv']['tmp_name'],'r');$headers=fgetcsv($handle);if(!$headers)wp_die('CSV trống.');$headers=array_map(function($h){return sanitize_key(preg_replace('/^\xEF\xBB\xBF/','',$h));},$headers);$done=0;$skipped=0;$dry=!empty($_POST['dry_run']);while(($row=fgetcsv($handle))!==false){$data=array_combine($headers,array_pad($row,count($headers),''));if(!$data||empty($data['name'])){$skipped++;continue;}$sku=sanitize_text_field($data['sku']??'');$id=absint($data['id']??0);if(!$id&&$sku){$found=get_posts(array('post_type'=>Slim_Catalog_Post_Types::POST_TYPE,'fields'=>'ids','posts_per_page'=>1,'meta_key'=>'_slim_sku','meta_value'=>$sku));$id=$found?(int)$found[0]:0;}if($dry){$done++;continue;}$post=array('post_type'=>Slim_Catalog_Post_Types::POST_TYPE,'post_title'=>sanitize_text_field($data['name']),'post_name'=>sanitize_title($data['slug']??''),'post_status'=>in_array($data['status']??'',array('publish','draft','private'),true)?$data['status']:'publish','post_content'=>wp_kses_post($data['description']??''));if($id)$post['ID']=$id;$id=wp_insert_post($post);if(is_wp_error($id)||!$id){$skipped++;continue;}foreach(array('_slim_sku'=>'sku','_slim_price'=>'regular_price','_slim_sale_price'=>'sale_price','_slim_short_description'=>'short_description','_slim_badge'=>'badge','_slim_cta_mode'=>'cta_mode','_slim_cta_label'=>'cta_label','_slim_cta_hotline'=>'cta_hotline','_slim_cta_url'=>'cta_url','_slim_cta_recipient'=>'cta_recipient')as$meta=>$col)update_post_meta($id,$meta,sanitize_text_field($data[$col]??''));update_post_meta($id,'_slim_featured',!empty($data['featured'])?'1':'');$cats=array_filter(array_map('trim',explode('|',$data['categories']??'')));if($cats)wp_set_object_terms($id,$cats,Slim_Catalog_Post_Types::TAXONOMY);$done++;}fclose($handle);wp_safe_redirect(add_query_arg(array('post_type'=>Slim_Catalog_Post_Types::POST_TYPE,'page'=>'slim-catalog-import-export','imported'=>$done,'skipped'=>$skipped),admin_url('edit.php')));exit; }
}
Slim_Catalog_Import_Export::init();
