<?php
/** Privacy-friendly aggregate product statistics. */
defined('ABSPATH')||exit;
final class Slim_Catalog_Product_Stats {
	const OPTION='tnstack_product_stats';
	public static function init(){add_action('wp_ajax_tnstack_product_event',array(__CLASS__,'event'));add_action('wp_ajax_nopriv_tnstack_product_event',array(__CLASS__,'event'));add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_post_tnstack_clear_product_stats',array(__CLASS__,'clear'));}
	public static function menu(){add_submenu_page('edit.php?post_type='.Slim_Catalog_Post_Types::POST_TYPE,'Thống kê','Thống kê',TNStack_Account_Permissions::ACCESS_CAP,'slim-catalog-stats',array(__CLASS__,'page'));}
	public static function event(){check_ajax_referer('tnstack_product_stats','nonce');$id=absint($_POST['product_id']??0);$event=sanitize_key(wp_unslash($_POST['event']??''));if(!self::record($id,$event))wp_send_json_error(null,400);wp_send_json_success();}
	public static function record($id,$event){$id=absint($id);if(!$id||Slim_Catalog_Post_Types::POST_TYPE!==get_post_type($id)||!in_array($event,array('view','hotline','form'),true))return false;$all=(array)get_option(self::OPTION,array());$day=gmdate('Y-m-d');if(!isset($all[$day]))$all[$day]=array();if(!isset($all[$day][$id]))$all[$day][$id]=array('view'=>0,'hotline'=>0,'form'=>0);$all[$day][$id][$event]++;ksort($all);if(count($all)>365)$all=array_slice($all,-365,null,true);update_option(self::OPTION,$all,false);return true;}
	public static function clear(){if(!current_user_can(TNStack_Account_Permissions::MANAGE_CAP))wp_die('Bạn không có quyền.');check_admin_referer('tnstack_clear_product_stats');delete_option(self::OPTION);wp_safe_redirect(admin_url('edit.php?post_type='.Slim_Catalog_Post_Types::POST_TYPE.'&page=slim-catalog-stats'));exit;}
	public static function page(){if(!current_user_can(TNStack_Account_Permissions::ACCESS_CAP))return;$days=max(7,min(365,absint($_GET['days']??30)));$since=strtotime('-'.($days-1).' days');$totals=array();foreach((array)get_option(self::OPTION,array())as$date=>$products){if(strtotime($date)<$since)continue;foreach($products as$id=>$counts){if(!isset($totals[$id]))$totals[$id]=array('view'=>0,'hotline'=>0,'form'=>0);foreach($totals[$id]as$key=>$v)$totals[$id][$key]+=absint($counts[$key]??0);}}uasort($totals,function($a,$b){return array_sum($b)-array_sum($a);});$sum=array('view'=>0,'hotline'=>0,'form'=>0);foreach($totals as$c)foreach($sum as$k=>$v)$sum[$k]+=$c[$k];?>
	<div class="wrap sc-stats"><h1>Thống kê sản phẩm</h1><p>Dữ liệu tổng hợp, không lưu IP hay thông tin định danh khách truy cập.</p><div class="sc-stats-filter"><form><input type="hidden" name="post_type" value="<?php echo esc_attr(Slim_Catalog_Post_Types::POST_TYPE);?>"><input type="hidden" name="page" value="slim-catalog-stats"><select name="days" onchange="this.form.submit()"><option value="7" <?php selected($days,7);?>>7 ngày</option><option value="30" <?php selected($days,30);?>>30 ngày</option><option value="90" <?php selected($days,90);?>>90 ngày</option><option value="365" <?php selected($days,365);?>>365 ngày</option></select></form><?php if(current_user_can(TNStack_Account_Permissions::MANAGE_CAP)):?><a class="button" onclick="return confirm('Xóa toàn bộ thống kê?')" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=tnstack_clear_product_stats'),'tnstack_clear_product_stats'));?>">Xóa dữ liệu</a><?php endif;?></div><div class="sc-stat-cards"><section><span>Lượt xem</span><strong><?php echo number_format_i18n($sum['view']);?></strong></section><section><span>Nhấp hotline</span><strong><?php echo number_format_i18n($sum['hotline']);?></strong></section><section><span>Gửi form</span><strong><?php echo number_format_i18n($sum['form']);?></strong></section><section><span>Tỷ lệ chuyển đổi</span><strong><?php echo $sum['view']?esc_html(number_format_i18n(($sum['hotline']+$sum['form'])/$sum['view']*100,1)).'%':'0%';?></strong></section></div><table class="widefat striped"><thead><tr><th>Sản phẩm</th><th>Lượt xem</th><th>Nhấp hotline</th><th>Gửi form</th><th>Chuyển đổi</th></tr></thead><tbody><?php if(!$totals):?><tr><td colspan="5">Chưa có dữ liệu.</td></tr><?php else:foreach($totals as$id=>$c):?><tr><td><a href="<?php echo esc_url(get_edit_post_link($id));?>"><strong><?php echo esc_html(get_the_title($id));?></strong></a></td><td><?php echo number_format_i18n($c['view']);?></td><td><?php echo number_format_i18n($c['hotline']);?></td><td><?php echo number_format_i18n($c['form']);?></td><td><?php echo $c['view']?esc_html(number_format_i18n(($c['hotline']+$c['form'])/$c['view']*100,1)).'%':'0%';?></td></tr><?php endforeach;endif;?></tbody></table></div><style>.sc-stats{max-width:1100px}.sc-stats-filter{display:flex;justify-content:space-between;margin:18px 0}.sc-stat-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:20px}.sc-stat-cards section{padding:20px;border:1px solid #dbe3ef;border-radius:14px;background:#fff}.sc-stat-cards span{display:block;color:#64748b}.sc-stat-cards strong{display:block;margin-top:8px;font-size:28px;color:#1d4ed8}@media(max-width:782px){.sc-stat-cards{grid-template-columns:1fr 1fr}}</style><?php }
}
Slim_Catalog_Product_Stats::init();
